name: virtual_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  permission_handler: ^11.0.1
  google_fonts: ^5.0.0
  google_mlkit_face_detection: ^0.10.1
  google_mlkit_commons: ^0.7.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jewel.png
    - assets/pink.png
    - assets/necklace1.png
    - assets/necklace2.png
    - assets/necklace3.png
    - assets/necklace4.png
    - assets/necklace5.png
    - assets/necklace6.png
